class Motion
class Accessibility

class Trait
None=UIAccessibilityTraitNone
Button=UIAccessibilityTraitButton
Link=UIAccessibilityTraitLink
Search_Field=UIAccessibilityTraitSearchField
Image=UIAccessibilityTraitImage
Selected=UIAccessibilityTraitSelected
Keyboard_Key=UIAccessibilityTraitKeyboardKey
Static_Text=UIAccessibilityTraitStaticText
Summary_Element=UIAccessibilityTraitSummaryElement
Plays_Sound=UIAccessibilityTraitPlaysSound
Starts_Media_Session=UIAccessibilityTraitStartsMediaSession
Updates_Frequently=UIAccessibilityTraitUpdatesFrequently
Adjustable=UIAccessibilityTraitAdjustable
Allows_Direct_Interaction=UIAccessibilityTraitAllowsDirectInteraction
Causes_Page_Turn=UIAccessibilityTraitCausesPageTurn
Not_Enabled=UIAccessibilityTraitNotEnabled
end

end
end
